### ISSUE TITLE
ft_strlen is dangerous!

### ISSUE THREAD

**Issue by andmadri** [Chr-ss/libft#3]
Dear Chriss,
Your ft_strlen is perilous. You are derefencing and moving a pointer which causes segmentation faults. I hope you fix it right away as you are using ft_strlen a lot.

**Comment by Chr-ss** [comment]
fixed in [3667ba4](https://github.com/Chr-ss/libft/commit/3667ba4db30e6add677a763c829d4c47890b2a8c)
